# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master
  - azure-pipeline

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - task: Docker@1
    displayName: 'Run db'
    inputs:
      imageName: 'postgres:alpine'
      command: 'run'
      containerName: db
      ports: 5432
      environmentVariables:
        POSTGRES_USER: wa
        POSTGRES_PASSWORD: wa
        POSTGRES_DB: wa
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'verify'
